name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: latency-lingo/github-action@v0.0.2
        with: 
          filename: scripts/test.js
