name: Teste de Performance com K6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do K6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Executar o Teste de Performance
        run: k6 run exemplo.js

      - name: Salvar Relatório de Performance
        uses: actions/upload-artifact@v2
        with:
          name: k6-performance-report
          path: /tmp/k6-result.json