name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3
      
      - name: Configuração do K6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Executar o Teste de Performance
        run: k6 run exemplo.js

      - name: Salvar Relatório de Performance
        uses: actions/upload-artifact@v2
        with:
          name: k6-performance-report
          path: /tmp/k6-result.json